-- ADFORGE AI minimal member/order schema.
-- Run this in Supabase SQL Editor after creating the project and enabling Google provider.

-- Admin allowlist used by RLS policies. Keep this in sync with assets/admin.js.
-- Current owner/admin Google account: b989010@gmail.com

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  display_name text,
  line_id text,
  credits integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  contact_name text,
  contact_email text,
  product_name text not null,
  package_type text not null,
  amount_ntd integer not null default 0,
  platform text,
  line_id text,
  target_style text,
  deadline text,
  image_link text,
  notes text,
  admin_notes text,
  payment_status text not null default 'not_required',
  payment_provider text,
  payment_method text,
  merchant_trade_no text,
  transaction_id text,
  checkout_url text,
  payment_amount_ntd integer,
  currency text not null default 'TWD',
  paid_at timestamptz,
  payment_error text,
  payment_expires_at timestamptz,
  payment_raw_payload jsonb,
  status text not null default 'pending' check (
    status in ('pending', 'confirmed', 'making', 'done', 'new', 'reviewing', 'quoted', 'in_progress', 'delivered', 'cancelled')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists name text,
  add column if not exists line_id text,
  add column if not exists credits integer not null default 0,
  add column if not exists updated_at timestamptz not null default now();

alter table public.orders
  add column if not exists contact_name text,
  add column if not exists contact_email text,
  add column if not exists amount_ntd integer not null default 0,
  add column if not exists target_style text,
  add column if not exists deadline text,
  add column if not exists image_link text,
  add column if not exists admin_notes text,
  add column if not exists payment_status text not null default 'not_required',
  add column if not exists payment_provider text,
  add column if not exists payment_method text,
  add column if not exists merchant_trade_no text,
  add column if not exists transaction_id text,
  add column if not exists checkout_url text,
  add column if not exists payment_amount_ntd integer,
  add column if not exists currency text not null default 'TWD',
  add column if not exists paid_at timestamptz,
  add column if not exists payment_error text,
  add column if not exists payment_expires_at timestamptz,
  add column if not exists payment_raw_payload jsonb;

alter table public.orders
  alter column status set default 'pending';

alter table public.orders
  drop constraint if exists orders_status_check,
  add constraint orders_status_check check (
    status in ('pending', 'confirmed', 'making', 'done', 'new', 'reviewing', 'quoted', 'in_progress', 'delivered', 'cancelled')
  );

alter table public.orders
  drop constraint if exists orders_package_type_check,
  add constraint orders_package_type_check check (
    package_type in ('free_diagnosis', 'trial_399', 'batch_999', 'page_2999', 'monthly_6900')
  );

alter table public.orders
  drop constraint if exists orders_amount_ntd_check,
  add constraint orders_amount_ntd_check check (amount_ntd >= 0);

alter table public.orders
  drop constraint if exists orders_payment_status_check,
  add constraint orders_payment_status_check check (
    payment_status in ('not_required', 'pending', 'checkout_created', 'paid', 'failed', 'expired', 'refunded')
  );

alter table public.orders
  drop constraint if exists orders_payment_amount_ntd_check,
  add constraint orders_payment_amount_ntd_check check (payment_amount_ntd is null or payment_amount_ntd >= 0);

create index if not exists orders_user_id_created_at_idx
  on public.orders (user_id, created_at desc);

create index if not exists orders_status_created_at_idx
  on public.orders (status, created_at desc);

create unique index if not exists orders_merchant_trade_no_unique_idx
  on public.orders (merchant_trade_no)
  where merchant_trade_no is not null;

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  provider text not null,
  merchant_trade_no text,
  transaction_id text,
  amount_ntd integer,
  status text,
  verified boolean not null default false,
  raw_payload jsonb,
  error_message text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.payment_transactions enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can read own orders" on public.orders;
create policy "Users can read own orders"
  on public.orders for select
  using (auth.uid() = user_id);

drop policy if exists "Admins can read all orders" on public.orders;
create policy "Admins can read all orders"
  on public.orders for select
  using (lower(auth.jwt() ->> 'email') = 'b989010@gmail.com');

drop policy if exists "Users can create own orders" on public.orders;
create policy "Users can create own orders"
  on public.orders for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own draft orders" on public.orders;

drop policy if exists "Admins can update order status" on public.orders;
create policy "Admins can update order status"
  on public.orders for update
  using (lower(auth.jwt() ->> 'email') = 'b989010@gmail.com')
  with check (lower(auth.jwt() ->> 'email') = 'b989010@gmail.com');

revoke update on public.orders from authenticated;
revoke update on public.profiles from authenticated;
revoke all on public.payment_transactions from authenticated;
grant select, insert on public.profiles to authenticated;
grant select, insert on public.orders to authenticated;
grant update (id, email, name, display_name, line_id, updated_at) on public.profiles to authenticated;
grant update (status, admin_notes, updated_at) on public.orders to authenticated;

create or replace function public.package_amount(package text)
returns integer
language sql
immutable
as $$
  select case package
    when 'trial_399' then 399
    when 'batch_999' then 999
    when 'page_2999' then 2999
    when 'monthly_6900' then 6900
    else 0
  end
$$;

create or replace function public.normalize_order_defaults()
returns trigger
language plpgsql
as $$
begin
  new.amount_ntd = public.package_amount(new.package_type);

  if tg_op = 'INSERT' then
    new.payment_status = case
      when new.amount_ntd > 0 then 'pending'
      else 'not_required'
    end;
    new.status = 'pending';
  end if;

  return new;
end;
$$;

drop trigger if exists orders_normalize_defaults on public.orders;
create trigger orders_normalize_defaults
  before insert or update on public.orders
  for each row execute function public.normalize_order_defaults();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', '')
  )
  on conflict (id) do update
    set email = excluded.email,
        name = excluded.name,
        display_name = excluded.display_name,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
