-- ADFORGE AI minimal member/order schema.
-- Run this in Supabase SQL Editor after creating the project and enabling Google provider.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  line_id text,
  credits integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  contact_name text,
  contact_email text,
  product_name text not null,
  package_type text not null,
  amount_ntd integer not null default 0,
  platform text,
  line_id text,
  target_style text,
  deadline text,
  image_link text,
  notes text,
  payment_status text not null default 'not_required',
  status text not null default 'new' check (
    status in ('new', 'reviewing', 'quoted', 'in_progress', 'delivered', 'cancelled')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists line_id text,
  add column if not exists credits integer not null default 0,
  add column if not exists updated_at timestamptz not null default now();

alter table public.orders
  add column if not exists contact_name text,
  add column if not exists contact_email text,
  add column if not exists amount_ntd integer not null default 0,
  add column if not exists target_style text,
  add column if not exists deadline text,
  add column if not exists image_link text,
  add column if not exists payment_status text not null default 'not_required';

create index if not exists orders_user_id_created_at_idx
  on public.orders (user_id, created_at desc);

create index if not exists orders_status_created_at_idx
  on public.orders (status, created_at desc);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can read own orders" on public.orders;
create policy "Users can read own orders"
  on public.orders for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create own orders" on public.orders;
create policy "Users can create own orders"
  on public.orders for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own draft orders" on public.orders;
create policy "Users can update own draft orders"
  on public.orders for update
  using (auth.uid() = user_id and status in ('new', 'reviewing'))
  with check (auth.uid() = user_id and status in ('new', 'reviewing'));

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', '')
  )
  on conflict (id) do update
    set email = excluded.email,
        display_name = excluded.display_name,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
